-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
	kind = {
		Text = "",
		Method = "m",
		Function = "",
		Constructor = "",
		-- Method = "",
		-- Function = "",
		-- Constructor = "",
		Field = "",
		Variable = "",
		-- Variable = "",
		Class = "",
		Interface = "",
		-- Module = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		-- Keyword = "",
		Snippet = "",
		-- Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
	type = {
		Array = "",
		Number = "",
		String = "",
		Boolean = "蘒",
		Object = "",
	},
	documents = {
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
	},
	git = {
		-- Add = "",
		-- Mod = "",
    Mod = "契",
		Remove = "",
		Ignore = "",
		Rename = "",
		Diff = "",
		Repo = "",
		Octoface = "",
	},
	ui = {
		ArrowClosed = "",
    ArrowRight = "➜",
		ArrowOpen = "",
    Plus = "+",
    IndentChar = "▏",
		Lock = "",
		Circle = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		Close = "",
    CloseCircle = "",
    LeftCircle = "",
    RightCircle = "",
    Modified = "●",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = "",
    SelectionCaret = " ",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		SignOut = "",
		Check = "",
		Fire = "",
		Note = "",
		BookMark = "",
		Pencil = "",
		-- ChevronRight = "",
		ChevronRight = ">",
		Table = "",
		Calendar = "",
		CloudDownload = "",
	},
	diagnostics = {
		Error = " ",
		Warning = " ",
		Information = "",
		Question = "",
		Hint = "",
    Added = " ",
    Modified =  " ",
    Removed = " ",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
		Smiley = "ﲃ",
		Package = "",
		CircuitBoard = "",
	},
}
