#!/bin/bash

# https://github.com/FelixKratz/JankyBorders

# brew services start borders
options=(
	style=round
	width=6.0
	hidpi=off
	#active_color=0xffe2e2e3
  active_color="gradient(top_left=0xffFF0000,bottom_right=0xff00FF00)"
	inactive_color=0xff414550
)

borders "${options[@]}"
