after-login-command = []
after-startup-command = []
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = 'move-mouse window-lazy-center'

accordion-padding = 30

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left' # See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-f = 'fullscreen'

alt-shift-h = 'move left' # See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50' # See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1' # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-shift-1 = 'move-node-to-workspace 1' # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

alt-tab = 'workspace-back-and-forth' # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next' # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor

# alt-enter = 'exec-and-forget /Applications/WezTerm.app/Contents/MacOS/wezterm'
alt-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty'
alt-shift-semicolon = 'mode service'
[mode.service.binding]
slash = ['exec-and-forget ~/dotfiles/configs/aerospace/show_keys.sh'] # slash(/) is same as key as ?
l = ['exec-and-forget ~/dotfiles/configs/aerospace/show_lst.sh']
r = ['reload-config', 'mode main', 'exec-and-forget ~/dotfiles/scripts/code/notify.sh "Reloaded config"']
t = ['layout floating tiling', 'mode main', 'exec-and-forget ~/dotfiles/scripts/code/notify.sh "Toggled layout"'] # Toggle between floating and tiling layout
equal = ['flatten-workspace-tree', 'mode main', 'exec-and-forget ~/dotfiles/scripts/code/notify.sh "Reset layout"'] # reset layout
esc = ['mode main']

alt-h = ['join-with left', 'mode main']
alt-j = ['join-with down', 'mode main']
alt-k = ['join-with up', 'mode main']
alt-l = ['join-with right', 'mode main']
