#!/bin/bash

# echo "Running: /Users/gians/dotfiles/scripts/playSDO.sh"
echo "Running: $0"

links=(
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aad Steh Jugad Steh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aadhi Such Jugaadi Such.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aae Mil Gurasikh Aae Mil.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aae Milahu Santh Sajanaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aaisaa Satigur Je Milai Tis No Sir Saupeeaai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aaisee Jaanee Sant Janee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aanad rang binod hamaarai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aanand aanand sabh ko kahai - 1983.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aanand aanand sabh ko kahai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aanandh Aanandh Sabh Ko Kehai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ab Mohi Needh Suhaavai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aisaa giaan veechaarey koee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aisaa Jag Dhaekhiaa Jooaaree.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aisaa Maeraa Raam Rehiaa Bharapoor.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aisaa meyraa raam rahiaa bharpoor.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aisee Gyaani Sant Janee - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Amrit Har Ka Naam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Amrith naam nidhhaan hai mil peevahu bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anmrith Naam Nidhhaan Hai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anmrith Naam Suaamee Thaeraa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anmrith Naam Suaamee Thaeraa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anmrith Ras Peeaa Gur Sabadhee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anmrith Sadhaa Varasadhaa Boojhan Boojhanehaar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Anthar Piaas Chaathrik Jio Jal Kee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apanae Kaaj Ko Kio Alakaaeeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apanae Prabh Sio Hohu Saavadhhaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apnay Jun Prubh Aap.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apnay Kaaj Ko.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apnay Raam Piaaray.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Apney prabh sio hoh saavdhaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/As Kridaan Khando Khadag.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Asa Ki Var.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ath Ootham Har Naam Hai Maeree Jindhurreeeae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Aykaa Aykunkar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Baanee Moukhahu Ouchaareeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Baaranai Balihaaranai Lakh Bareeaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bahuth Vaddiaaeeaa Saahibai Neh Jaahee Ganeeaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bal Bal Bal Guradhaev Jin Naam Dhrirraaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhaaee Rae Mo Ko Koee Aae Milai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagat Sohey Guhn Gavday.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagataa Kee Tek Toon Santaa Kee Ot Toon 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagataa Kee Tek Toon Santaa Kee Ot Toon 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagataa Kee Tek Toon Santaa Kee Ot Toon 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagath Sohehi Gun Gaavathae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagath Sohehi Gun Gaavathae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagathaa Kaa Sehaaee Jug Jug Jaaniaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhagtaa kaa saahaaee jug jug jaaniaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhaj Man Maerae Eaeko Naam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhalae Amaradhaas Gun Thaerae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhinee rainarheeai chaamkan taarey.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhinnee Rain Jinhaa Man Chaao.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhinnee Rainarreeai Chaamakan Thaarae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bhinnee Rainarreeai Chaamakan Thaarae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bibeyk budh beechaar gurmukh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bikhamo Bikham Akhaaraa Mai Gur Mil Jeetaa Raam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bikhamo bikham akhaarhaa mai gur mil jeetaa raam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin Ek Naam Ik Chitt Loon.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin gur mukat na paaeeai bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin gur mukat na paeeai bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin Gur Mukath N Paaeeai Bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin Sabaday Achaar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Bin Sadhu Kion Jeevana with Bibi Harjit Kaur - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chadayee Leeo Maha Baleetai - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chinthaa Dhhaavath Rehi Geae Thaan Man Bhaeiaa Anandh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chirree Chuhakee Pahu Futtee 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chirree Chuhakee Pahu Futtee 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chit cheytas kee nahee baavariaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Chit Na Bhayo Hamro Aavan Kah.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Deykhoh acharaj bheiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhaekhahu Acharaj Bhaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhann Guroo Dhannu Guroo Piaaray.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhanu Naanak Tayree Vadee Kamaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhhann S Vaelaa Jith Mai Sathigur Miliaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhhann S Vaelaa Jith Mai Sathigur Miliaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhin Bhee Gaavau Rainee Gaavau.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhin Rain Saas Saas Gun Gaavaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhukhee Dhunee Sehaerreeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dhunwant Naam Kay Vanjaray.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Dukhee Dunee Suheyreeay.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Eae Man Maeriaa Thoo Kiaa Lai Aaeiaa Kiaa Lai Jaaeisee Raam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Eae Man Piaariaa Thoo Sadhaa Sach Samaalae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Eae Sareeraa Maeriaa Eis Jag Mehi Aae Kai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Eihu Man Har Kai Naam Oudhhaaranaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/With Maarag Chaliyai Bhayiare - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Fareedaa raat kathooree vanddeeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Fareedhaa Raath Kathhooree Vanddeeai 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Fareedhaa Raath Kathhooree Vanddeeai 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gagan Dhamaamaa Baajio Pario Neesaanai Ghaau.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gobind Gun Gaavan Laagay.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gobindh Jeeo Maerae Man Than Naam Har Beedhhae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gobindh Jeeo Maerae Man Than Naam Har Beedhhae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gobindh Jeeo Maerae Man Than Naam Har Beedhhae 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Kaa Sabadh Anmirat Hai Baanee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Kaa Sabadh Maerai Anthar Dhiaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur kaa shabad meyrai antar dhiaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Kee Baanee Vittahu Vaariaa Bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Kuhea Joothi Dhoi.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Parasaadh Sehaj Ghar Paaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Parasaadhee Bho Paeiaa Vaddabhaag Vasiaa Man Aae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Poore Te Paieeaai Hiradhai Dhei Dhikhaiee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Sathigur Vich Naavai Kee Vaddee Vaddiaaee 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Sathigur Vich Naavai Kee Vaddee Vaddiaaee 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Sathigur Vich Naavai Kee Vaddee Vaddiaaee 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Shabadi Gobind Gajeya - India 1970s with Gorai Sikhs.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gur Sikhee Bareek Hai %28Bhai Gurdas%29.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurabaanee Sun Mail Gavaae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurabaanee Sun Mail Gavaae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurabaanee Sun Mail Gavaae 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Guramukh Naam Sunahu Maeree Bhainaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Guramukh Saevaa Ghaal Jin Ghaalee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurasikhaan Man Har Preeth Hai Gur Poojan Aavehi.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurbaannee sunn mail gavaaey - Smethwick %28UK%29 1983.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gurmukh rang chalooliaa meyraa man tano bhinaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Guroo Guroo Gur Kar Man Mere.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gursikhan Kee Bhukh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gursikhan Man Har Preet Hai with Bibi Harjit Kaur - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Gursikhi Bareek Hai - 1979.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Hamaraa Thaakur Sabh Thae Oochaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Hamarae Pithaa Thaakur Prabh Suaamee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Hamaree Jaath Paath Gur Sathigur Ham Vaechiou Sir Gur Kae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Bin Sabh Kishh Mailaa Santhahu.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Har Japun Japoon Dhin Ratee - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Har Rasanaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Jan Dhaekhahu Sathigur Nainee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Jan Raam Raam Raam Dhiaane.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Japat Rahan - 22nd May 1966.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Jeeau Tudh Vitahu Bal Jaiee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Kae Naam Bin Jhoothae Sagal Paasaarae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Kae Santh Sunahu Jan Bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Kee Thum Saevaa Karahu.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Kee Ttehal Kamaavanee Japeeai Prabh Kaa Naam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Keeratan Gaavahu Dhin Raatee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har keertan gaavo din raatee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Naamai Kee Ham Kano Sathigur Kaarakunee Dheeee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Raam Naam Jap Laahaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Rasak Rasak Gun - 1979.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Siau Jurai Ta Sabh Ko Meet.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har simree din sabh rainn.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Har Sion Juray.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Hasandhiaa Khaelandhiaa Painandhiaa Khaavandhiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ho Bhaal Vikunnee Hoee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ho Bhee Ouddeenee Kanth Ko Anmaalee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Hoho Sabdaan Apney Prub Sion.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Humaarai Ekai Haree.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ihn Bee Gaavo Raenee Gaavo.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ik Jeej Mujai Deh - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ik Kharay Karay Teri.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ik Kharay Karay Teri2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ja Din Bhetay Sadh Mohey.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jaethae Ras Sareer Kae Thaethae Lagehi Dhukh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jaisee Mai Aavai Khasam Kee Baanee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jan Naanak Ko Kirapaa Bhee Har Kee Kirapaa Bhee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jap Jap Har Kaa Naam Kadhae N Jhooreeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jap Man Naam Haree Hohi Sarab Sukhee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jarhee Bootee Jay Jeeveeai Kiu Marai Dhanataru.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jeevan Padh Nirabaan Eiko Simareeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jeevanaa Safal Jeevan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jeevnaa Safal jeevan - December 1984.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jin Alakh Akaal Niranjana.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jin Jan Guramukh Saeviaa Thin Sabh Sukh Paae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jin kai har naam vasiaa sad hirdai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jin Kai Har Naam Vasiaa Sadh Hiradhai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jinaa Gurasikhaa Ko Har Santhusatt Hai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jinee Jinee Gurmukhey Dhiaya.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jinee Naam Dhhiaaeiaa Eik Man Eik Chith 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jinee Naam Dhhiaaeiaa Eik Man Eik Chith 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jinee Naam Dhiaya.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Jo Deesay So So Rogee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Jo Dheesai So So Rogee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Mai Baedhan Saa Kis Aakhaa Maaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Man Chith Eik Araadhhadhae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Man Chith Thudh Dhiaaeidhae Maerae Sachiaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Man Chith Thudh Dhiaaeidhae Maerae Sachiaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Man Chith Thudh Dhiaaeidhae Maerae Sachiaa 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Man Chith Thudh Dhiaaeidhae Maerae Sachiaa 4.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Jo Thudhh Sach Dhhiaaeidhae Sae Viralae Thhorrae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Joh Man Chit Ik Araadadhe - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kaatiaa Rog Maha Sukh Paya.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kahaa Bhayo Jo Dooolochanndmoondd Kai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kahu Naanak Gur Bharam Chukaaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kanthaa Thoo So Saejarree Maiddaa Habho Dhukh Oulaahi 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kanthaa Thoo So Saejarree Maiddaa Habho Dhukh Oulaahi 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kathaa puraatan io sunnee bhagtan kee baanee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Keerath Karan Saran Manamohan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Keertan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kio Reheeai Thhir Jag.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kirapaa Nidhhaan Preetham Prabh Maerae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Koee Aavai Santho Har Kaa Jan Santho.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Koi Nindak Vadiaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Koor Nikhute Naanakaa Orak Sach Rahee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Kou Jagay Har Jun.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Laaj Shod Har Kay Guhn Gaavay.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Loein Rathae Loeinee Kannee Surath Samaae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Charan Gur Meethae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Man Maero Bas Naahi.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee man meyro bas naahe.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Ree Maathee Charan Samooh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Ree Man Maero Mathavaaro.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee ree man meyro matvaaro.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Ree Matee Charan Sumoo.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaee Sath Sath Sath Har Sath Sath Sath Saadhhaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maaeiaa Aisee Mohanee Bhaaee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maee Sti Sti Sti.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maerae Man Saev Safal Har Ghaal.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maerae Raam Ham Paapee Saran Parae Har Dhuaar 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maerae Raam Ham Paapee Saran Parae Har Dhuaar 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maerae Raam Thorr Bandhhan Maaeiaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maerae Raam Thorr Bandhhan Maaeiaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Maeree Patteeaa Likh Dhaehu Sree Guopaal.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Magan bhae oohaa sang maate - Southbend September 30 1985.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Magan Bheae Oohaa Sang Maathae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mai Sat Sat Sat - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Man eyk na cheytas moorh manaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Man Mere Gur Sabadhee Har Paiaa Jai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Man Rae Thhir Rahu Math Kath Jaahee Jeeo.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mayee Man Mero Matvaro - India 1970s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mayee Ree Maati Charan Samoo - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mera Mun Laagaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mere Raam Hum Paapi.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mere ram hum papee saran pare har duaar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mil Mere Preetma Jeo.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mil Raheeaai Prabh Saadh Janaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mil Raheeaai Prabh Saadh Janaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mil Raheeyai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mil Rheeay Prubh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Milahu Piaarae Jeeaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mitt Gee Bhaal Man Sehaj Samaanaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mo Ko Sathigur Sabadh Bujhaaeiou.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mohe Nirgun Anaath - India 1970s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mukh Bolahu Gur Anmrith Bainaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mul Khareedhee Laalaa Golaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Mul Khareedhee Laalaa Golaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naam Binaa Nahi.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naam Biouhaaraa Naanak Aadhhaaraa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naam kahat govind kaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naam Kehath Govindh Kaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naanak Ghar Hee Baithiaa Sahu Milai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Naktee Ko Thangan Baada.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Nanak Daas Tuajai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Nanak Gur Seyvaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Oohoo Saav Dhaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Oucharahu Raam Naam Lakh Baaree.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Paarabreham Thin Kano Santhusatt Bhaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Paatisaahaan Dee Majalasai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Paradhes Jhaag Saudhe Kau Aaiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Paraethahu Keethon Dhaevathaa Thin Karanaihaarae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Pardeys chjaag saudey kau aaiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Peeoo Dhaadhae Kaa Khol Ddithaa Khajaanaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Piaarae ein bidhh milan n jaaee mai keeeae karam anaekaa - Southbend Rainsabai September 30 1985 - part 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Piaarae Har Bin Praem N Khaelasaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Piaarae Har Bin Praem N Khaelasaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Pooran Raj Jog.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Poore Gur Kee Dhekh Vaddaiee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Poorey gur kee kaar karam kamaaeeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Pothhee Paramaesar Kaa Thhaan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Prabh Keejai Kirapaa Nidhhaan Ham Har Gun Gaavehagae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Prabh Milanai Kee Eaeh Neesaanee 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Prabh Milanai Kee Eaeh Neesaanee 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raajaa Raam Thoon Aisaa Nirabho.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raam Ham Sathigur Paarabreham Kar Maanae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raam Japahu Meree Sakhee Sakhainee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raam Naam Jap Eaekankaar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raam Ras Peeaa Rae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raam Ras Peeaa Rae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Raameeaa gun gaaeeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rae Man Maerae Thoon Har Sio Jor 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rae Man Maerae Thoon Har Sio Jor 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rae Man Maerae Thoon Har Sio Jor 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rae Moorrae Thoo Hoshhai Ras Lapattaaeiou.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Ram Hum Satgur Parbram.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rameeaa Gun Gaaeeai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rameyeeaa gun gaaeeai2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Re Man Moor Simar Sukhadhaataa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Rehras Sahib.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saach Naam Meraa Man Laagaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saach Naam Meraa Man Laagaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saachai Saahib Rakhiaa Kanth Laae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saad Sange Vanjareya - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saadhasang Kal Keeratan Gaiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saadhhasangath Kai Aasarai Prabh Sio Rang Laaeae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saadhhoo Bin Aisae Abagath Jaavai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saadhsangat kai aasrai prabh sio rang laaey.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saaee Naam Amol Keem N Koee Jaanadho 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saaee Naam Amol Keem N Koee Jaanadho 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saaee Naam Amol Keem N Koee Jaanadho 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saas Saas Dhiaavho.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh dhan kaho gur satguroo.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh Dhhann Kehahu Gur Sathiguroo 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh Dhhann Kehahu Gur Sathiguroo 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh dhiavho aad state jugad state.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh Kal Oudhharee Eik Naam Dhharam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabh Kih Terai Was Hai Too Sachaa Saahu.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sabhanaa Oupaavaa Sir Oupaao Hai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sadh sangat kai aasrai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sae saah sachae vanajaariaa jin har dhan palai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sae Sanjog Karahu Maerae Piaarae 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sae Sanjog Karahu Maerae Piaarae 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saevee Sathigur Aapanaa Har Simaree Dhin Sabh Rain 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saevee Sathigur Aapanaa Har Simaree Dhin Sabh Rain 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saevee Sathigur Aapanaa Har Simaree Dhin Sabh Rain 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Saevee Sathigur Aapanaa Har Simaree Dhin Sabh Rain 4.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Safal Te Gharee Sanjog Suhaave.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Santh Janaa Kee Dhhoor Masathak Laaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Santh Sabhaa Mehi Bais K 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Santh Sabhaa Mehi Bais K 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Santh Sabhaa Mehi Bais K 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sat sat sat sat sat gurdeyv.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Satgur Shabad Oujaaro.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathasangath Sathigur Dhhann Dhhanuo Dhhann Dhhann Dhhano.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathigur Aagai Sees Bhaett Dhaeo 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathigur Aagai Sees Bhaett Dhaeo 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathigur Aagai Sees Bhaett Dhaeo 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathigur Miliai Sach Paaeiaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sathigur No Jaehaa Ko Eishhadhaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Satigur Gunee Nidhan Hay.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Satigur Ka Updaysh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Say Jun Suchay Suda Suda.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Aisaa Har Naam Dhhiaaeeai Man Maerae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So kichh kar jit chhutteh paraanee - Part 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So kichh kar jit chhutteh paraanee - Part 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Kishh Kar Jith Shhuttehi Paraanee 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Kishh Kar Jith Shhuttehi Paraanee 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Kishh Kar Jith Shhuttehi Paraanee 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Satgur Kaho sabh dhan dhan.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Sathagur Kehahu Sabh Dhhann Dhhann.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Sathigur Dhhan Dhhann Jin Bharam Garr Thorriaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Sukhadhaataa J Naam Japaavai 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Sukhadhaataa J Naam Japaavai 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/So Sukhadhaataa J Naam Japaavai 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Soee Hoaa Jo This Bhaanaa Avar N Kin Hee Keethaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sohila.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sravanee Keerathan Suno Dhin Raathee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sravanee Suniyai Rasna Gayiyai - India 1980s.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Suasath Aathh Baanee Baramaao 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Suasath Aathh Baanee Baramaao 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sucha Souda Hri Naam Hai.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sun Kai Saadh Maahee Dhaa 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sun Kai Saadh Maahee Dhaa 2.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sunho Loka Meh Praym.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Suniai Sidhh Peer Sur Naathh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sunoh Loka Mai Prem Ras Paya - 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Sureh Kee Jaisee Thaeree Chaal.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Tau kaarann saahibaa rang ratey.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thaerae Jan Dhaekhan Paavaa.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thin Ghar Raakhiarraa Juo Anadhin Jaagai Raam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thinee Sathigur Kee Gal Mannee.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Tho Kaaran Saahibaa Rang Rathae.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thoo Thaakuro Bairaagaro 1.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thoo Thaakuro Bairaagaro 2.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thoo Thaakuro Bairaagaro 3.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Thoo Thaakuro Bairaagaro 4.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Tin ghar raakhiarhaa jo andin jaagai raam.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Too Mere Gur Kay Piaaray.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Too Sagro Ratnagro.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Un Pekath He Kaal Karaseya - India 1980s.MP3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Vaah vaah gobind singh.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Vaar.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Vah Vah Gobindh Singh Apae Gur Chaela.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Vaisaakh Dhheeran Kio Vaadteeaa Jinaa Praem Bishhohu.mp3"
	"http://sikhsoul.com/golden_khajana_files/mp3/Keertan/Bhai Mohinder Singh SDO/Waheguru Gur Shabad Hai - India 1970s.MP3"

	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_1.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_11.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_13.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_15.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_17.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_19.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_20.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_22.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_24.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_26.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_28.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_3.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_31.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_33.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_35.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_5.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_7.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_9.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_10.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_12.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_14.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_16.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_18.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_2.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_21.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_23.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_25.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_27.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_30.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_32.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_34.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_4.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_6.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Vancouver_BC_1980s/Bhai_Mohinder_Singh_Jee_SDO_Vancouver_1980s_Vol_8.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Aanand aanand sabh ko kahai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Apney prabh sio hoh saavdhaan%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Bikhamo bikham akhaarhaa mai gur mil jeetaa raam%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Chit cheytas kee nahee baavariaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Gur kaa shabad meyrai antar dhiaan%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Har simree din sabh rainn%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Kathaa puraatan io sunnee bhagtan kee baanee%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Man eyk na cheytas moorh manaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Sabh dhan kaho gur satguroo%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28So kichh kar jit chhutteh paraanee%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Vaah vaah gobind singh%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1960s %28Fareedaa raat kathooree vanddeeai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1970s %28Bhinee rainarheeai chaamkan taarey%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1970s %28Maaee man meyro bas naahe%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1980s %28Aisaa giaan veechaarey koee%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1980s %28Naam kahat govind kaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Bradford-2 %28Ho aayaa dooroh chal kai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Detroit %28Pootaa maataa kee aasees%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Toledo %28Suast aath baannee barmaao%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Jee_SDO_Jaagat_Jot_Jappae_ Part_1.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Punjab_1970_1.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Punjab_1980_1.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Punjab_1980_3.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Smethwick_UK_01_10_83_Part_2.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Aanad rang binod hamaarai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Aisaa meyraa raam rahiaa bharpoor%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Bibeyk budh beechaar gurmukh%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Bin gur mukat na paaeeai bhaaee%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Deykhoh acharaj bheiaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Gurmukh rang chalooliaa meyraa man tano bhinaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Jin kai har naam vasiaa sad hirdai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Maaee ree man meyro matvaaro%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Rameyeeaa gun gaaeeai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Sat sat sat sat sat gurdeyv%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh %28Tau kaarann saahibaa rang ratey%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-%28Saadhsangat kai aasrai prabh sio rang laaey%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1960s %28Tin ghar raakhiarhaa jo andin jaagai raam%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1970s %28Har keertan gaavo din raatee%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1970s %28Poorey gur kee kaar karam kamaaeeai%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-1980s %28Bhagtaa kaa saahaaee jug jug jaaniaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Bradford-1 %28Pardeys chjaag saudey kau aaiaa%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Dayton 1980s %28Jeevnaa saphal jeevan%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-Southbend 1990 %28Har Har sant janaa kee jeevan%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhaaee Mohinder Singh-UK 1983 %28Gurbaannee sunn mail gavaaey%29.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Jee_SDO_Jaagat_Jot_Jappae_ Part_2.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Punjab_1970_2.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Punjab_1980_2.mp3"
	"https://www.ikirtan.com//Bhai_Mohinder_Singh_Jee_SDO/Bhai_Mohinder_Singh_Ji_SDO_Smethwick_UK_01_10_83_Part_1.mp3"
)

length=${#links[@]}
index=$((RANDOM % length))
random_item=${links[index]}
echo "Random item: $random_item"
open "$random_item"
