# set -g default-terminal "screen-256color"

# Start window and pane numbering at 1, (0 is too hard to reach).
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber window numbers on closing a pane (tmux >= 1.7).
set -g mouse on
bind | split-window -h # unbind %
bind - split-window -v # unbind '"'
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"
unbind K
bind K confirm-before kill-session \; display "Session killed!"
bind-key -r S run-shell "tmux neww ~/dotfiles/scripts/code/tmux_swap_windows.sh"


bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
# unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10


# from https://github.com/ericmckevitt/Dotfiles/blob/main/tmux.conf (https://www.youtube.com/watch?v=7BP9iWiKx8Q&t=149s)
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-t display-popup -d "#{pane_current_path}" -w 75% -h 75% -E "zsh"

##### STATUS BAR (TOP) #####
##### STATUS BAR STYLE (ARROWS / BLUE-BLACK) #####
set -g status-position top
set -g status on
set -g status-style bg=black,fg=colour117
set -g status-justify left
##### PANE BORDERS #####
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39
##### MESSAGE / MODE #####
set -g message-style bg=colour39,fg=black
setw -g mode-style bg=colour39,fg=black


##### LEFT SIDE #####
set -g status-left-length 100
# set -g status-left "#[fg=black,bg=colour39,bold] #S #[fg=colour39,bg=black,nobold]"
set -g status-left "#{battery_percentage} #[fg=black,bg=colour39,bold] #S #[fg=colour39,bg=black,nobold]" # from tmux-plugins/tmux-battery

##### RIGHT SIDE #####
# set -g status-right-length 100
# set -g status-right "#[fg=colour39,bg=black]#[fg=black,bg=colour39] %H:%M #[fg=colour39,bg=black]#[fg=black,bg=colour45] %Y-%m-%d "
set -g status-right "#{cpu_percentage} CPU" # from tmux-plugins/tmux-battery
# %Y-%m-%d %H:%M "

# Inactive window
setw -g window-status-format "  #I:#W #[fg=colour236,bg=black]"
# Active window
setw -g window-status-current-format "  #[fg=colour39,bg=black]#[fg=black,bg=colour39,bold] #I:#W #[fg=colour39,bg=black]"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Optional: nicer visuals (recommended)
# set -g @plugin 'erikw/tmux-powerline'
# set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/default/cyan'
# set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# prefix + I ; Installs new plugins from GitHub or any other git repository ; Refreshes TMUX environment
# prefix + U ; updates plugin(s)
# prefix + alt + u ; remove/uninstall plugins not on the plugin list
run '~/.tmux/plugins/tpm/tpm' # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
