live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "DroidSansMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001B[94;5u"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 10000

[window]
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
